name: Go Build and Docker

on:
  push:
    branches:
      - main
      - docker-pipeline

env:
  DOCKER_IMAGE_NAME: projet-devops
  DOCKER_REGISTRY_URL: ghcr.io
  DOCKER_USERNAME: teroaz

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.5'

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./webapi
          file: ./webapi/Dockerfile
          push: true
          tags: ${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}
