name: Go Build and Docker

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: projet-devops
  DOCKER_REGISTRY_URL: ghcr.io
  DOCKER_USERNAME: teroaz

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.5'

      - name: Install dependencies
        run: go mod tidy

      - name: Build application
        run: go build -o app ./webapi/main.go

  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.5'

      - name: Build binary
        run: go build -o app ./webapi/main.go

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}