name: Go Build and Docker

on:
  push:
    branches:
      - main
      - docker-pipeline
      - docker-with-buildpack

env:
  DOCKER_IMAGE_NAME: projet-devops
  DOCKER_REGISTRY_URL: ghcr.io
  DOCKER_USERNAME: teroaz

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.6'

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Install pack CLI
        run: |
          curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.29.0/pack-v0.29.0-linux.tgz" | tar xzv
          sudo mv pack /usr/local/bin/pack
          
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.6'

      - name: Build and push Docker image using Buildpacks
        run: |
          pack build ${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }} \
            --builder paketobuildpacks/builder:full \
            --path ./webapi
          
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ${{ env.DOCKER_REGISTRY_URL }} -u ${{ env.DOCKER_USERNAME }} --password-stdin
          docker push ${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}

